####################################################################################
#
#    Custom Vision Operalization
#
#    Microsoft
#   
####################################################################################
#
#    Azure Storage - Blob
# 
####################################################################################
azure_storage:
  container_name: 
  storage_name: 
  conn_string: 
  sas_token: 
####################################################################################
#
#   Custom Vision
# 
####################################################################################
cv:
  ProjectName: 'fruit-classifier-gerdau-new'
  Threshold: 0.8
  TrainingEndpoint: https://cmcustomvision.cognitiveservices.azure.com/
  TrainingKey: 8b5460f998a74816ad0f4d5c662defa7
  PredictionEndpoint: https://cmcustomvision-prediction.cognitiveservices.azure.com/
  PredictionKey: a53272898c6545a7a8d3f8b5a5d4ee5c
  PredictionResource: /subscriptions/8d47f388-3a7a-4970-9dec-2c6cc53e02a9/resourceGroups/rg_chihuahua_muffin/providers/Microsoft.CognitiveServices/accounts/cmcustomvision-prediction 
  ProjectID: 1bc40d6a-bd2c-46fe-b734-15bb03bf6a79