####################################################################################
#
#    Custom Vision Operalization
#
#    Microsoft
#   
####################################################################################
#
#    Azure Storage - Blob
# 
####################################################################################
azure_storage:
  container_name: 
  storage_name: 
  conn_string: 
  sas_token: 
####################################################################################
#
#   Custom Vision
# 
####################################################################################
cv:
  ProjectName: 'fruit-classifier'
  Threshold: 0.8
  TrainingEndpoint: 
  TrainingKey: 
  PredictionEndpoint: 
  PredictionKey: 
  PredictionResource: 
  ProjectID: 